# Generated by Django 4.2 on 2025-02-25 05:53
from django.db import migrations


def create_user_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    Task = apps.get_model('notes', 'Task')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    group, created = Group.objects.get_or_create(name='Пользователи приложения')
    if created:
        content_type = ContentType.objects.get(app_label='notes', model='task')
        permissions = Permission.objects.filter(content_type=content_type)
        group.permissions.set(permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0002_remove_task_description'),
    ]

    operations = [
        migrations.RunPython(create_user_group),
    ]
