# Generated by Django 4.2 on 2025-04-08 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_userheadertitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHeaderTitle',
            new_name='HeaderTitle',
        ),
    ]
